import { test } from "node:test";
import assert from "node:assert/strict";
import { buildSystemPac } from "../src/core/build.js";
import { parseScript } from "../src/core/analyze.js";
import { fixture, PSL } from "./support.js";

const MAIN = 'function FindProxyForURL(url, host) {\n  return "DIRECT";\n}';

function pacFor(...masks) {
  const test = masks.map((mask) => `root(host, ${JSON.stringify(mask)})`).join(" || ");
  return `function FindProxyForURL(url, host) {\n  if (${test}) return "PROXY p:1";\n  return "DIRECT";\n}`;
}

const build = (userPac, groups) => buildSystemPac(userPac, groups, PSL);

function referenceGroups() {
  return {
    "instagram.com": {
      rootHost: "www.instagram.com",
      hosts: {
        "static.cdninstagram.com": 1758450000000,
        "edge-chat.facebook.com": 1758450000001,
        "scontent-ams2-1.cdninstagram.com": 1758450000002,
      },
    },
  };
}

function generatedPart(text, userPac) {
  const index = text.indexOf(userPac);
  assert.notEqual(index, -1);
  return text.slice(0, index) + text.slice(index + userPac.length);
}

test("reference System PAC is reproduced byte for byte", () => {
  assert.equal(buildSystemPac(fixture("user.pac"), referenceGroups(), PSL), fixture("system.pac"));
});

test("output is deterministic", () => {
  const userPac = fixture("user.pac");
  assert.equal(buildSystemPac(userPac, referenceGroups(), PSL), buildSystemPac(userPac, referenceGroups(), PSL));
});

test("group and host insertion order does not matter", () => {
  const groups = { ...referenceGroups(), "fbcdn.net": { rootHost: null, hosts: {} } };
  const reordered = {
    "fbcdn.net": { rootHost: null, hosts: {} },
    "instagram.com": {
      rootHost: "www.instagram.com",
      hosts: Object.fromEntries(Object.entries(groups["instagram.com"].hosts).reverse()),
    },
  };
  const userPac = pacFor("instagram.com", "fbcdn.net");
  assert.equal(buildSystemPac(userPac, reordered, PSL), buildSystemPac(userPac, groups, PSL));
});

test("reordering root() in the User PAC leaves the generated part unchanged", () => {
  const groups = { ...referenceGroups(), "fbcdn.net": { rootHost: null, hosts: {} } };
  const a = pacFor("instagram.com", "fbcdn.net");
  const b = pacFor("fbcdn.net", "instagram.com");
  assert.equal(generatedPart(buildSystemPac(b, groups, PSL), b), generatedPart(buildSystemPac(a, groups, PSL), a));
});

test("colliding variable names get unique numeric suffixes in sorted mask order", () => {
  const empty = () => ({ rootHost: null, hosts: {} });
  const masks = ["a.b.com-2", "a.b.com", "a-b.com", "x.com", "x-x.com"];
  const text = build(pacFor(...masks), Object.fromEntries(masks.map((mask) => [mask, empty()])));
  const declared = [...text.matchAll(/^var (LEARNED_\w+) = \{$/gm)].map((m) => m[1]);
  const comments = [...text.matchAll(/^\/\/ root: (".*")$/gm)].map((m) => JSON.parse(m[1]));
  assert.deepEqual(comments, ["a-b.com", "a.b.com", "a.b.com-2", "x-x.com", "x.com"]);
  assert.deepEqual(declared, ["LEARNED_a_b_com", "LEARNED_a_b_com_2", "LEARNED_a_b_com_2_2", "LEARNED_x_x_com", "LEARNED_x_com"]);
  assert.match(text, /var __GROUPS = \[\n {2}LEARNED_a_b_com,\n {2}LEARNED_a_b_com_2,\n {2}LEARNED_a_b_com_2_2,\n {2}LEARNED_x_x_com,\n {2}LEARNED_x_com\n\];/);
  assert.match(text, /var __ROOTS = \[\n {2}"a-b\.com",\n {2}"a\.b\.com",\n {2}"a\.b\.com-2",\n {2}"x-x\.com",\n {2}"x\.com"\n\];/);
});

test("empty groups and empty registries", () => {
  const text = build(pacFor("a.com"), { "a.com": { rootHost: null, hosts: {} } });
  assert.match(text, /\/\/ root: "a\.com"\nvar LEARNED_a_com = \{\n {2}__proto__: null,\n {2}rootHost: null,\n {2}hosts: \{\n {4}__proto__: null\n {2}\}\n\};\n/);
  const none = buildSystemPac(MAIN, {}, PSL);
  assert.match(none, /^\/\/ Generated by RootPAC\. Do not edit\.\n\n\(function \(global\) \{\nvar __GROUPS = \[\];\n\nvar __ROOTS = \[\];\n\nvar __BYPASS_HOSTS = \[\];\n\nvar __BYPASS_SUBDOMAINS = \[\];\n\nvar __Error = Error;\n/);
  assert.match(none, /\n\}\)\(this\);\n\nvar __user = \(function \(\) \{\n/);
  assert.doesNotMatch(none, /LEARNED_/);
});

test("string literals are emitted through JSON.stringify", () => {
  const text = build(pacFor("a.com"), {
    "a.com": { rootHost: 'w"w\\w.a.com', hosts: { "x.b.com": 1 } },
  });
  assert.ok(text.includes('  rootHost: "w\\"w\\\\w.a.com",\n'));
  parseScript(text);
});

test("User PAC is embedded verbatim including multiline template literals", () => {
  const userPac = [
    "var banner = `line one",
    "    indented line",
    "\ttabbed ${1 + 1}`;",
    "  var  spaced   =  1 ;",
    MAIN,
  ].join("\n");
  const text = buildSystemPac(userPac, {}, PSL);
  assert.ok(text.includes(`var __user = (function () {\n${userPac}\nreturn FindProxyForURL;\n})();\n`));
});

test("a trailing newline in the User PAC is kept verbatim", () => {
  const text = buildSystemPac(`${MAIN}\n`, {}, PSL);
  assert.ok(text.includes(`${MAIN}\n\nreturn FindProxyForURL;\n`));
});

test("CRLF in the User PAC is preserved", () => {
  const userPac = MAIN.replace(/\n/g, "\r\n");
  assert.ok(buildSystemPac(userPac, {}, PSL).includes(`(function () {\n${userPac}\nreturn`));
});

test("output ends with a single newline", () => {
  const text = buildSystemPac(MAIN, {}, PSL);
  assert.ok(text.endsWith(`\n${MAIN}\nreturn FindProxyForURL;\n})();\n`));
  assert.equal(text.split("\n").at(-1), "");
});

test("invariant violations fail fast", () => {
  const group = (rootHost, hosts) => ({ rootHost, hosts });
  const one = pacFor("a.com");
  const two = pacFor("a.com", "c.com");
  const denied = `deny("*.ads.net");\n${pacFor("a.com")}`;
  assert.throws(() => buildSystemPac(null, {}, PSL), TypeError);
  assert.throws(() => build(one, null), TypeError);
  assert.throws(() => build(one, new Map()), TypeError);
  assert.throws(() => build(one, { "a.com": { rootHost: null } }), TypeError);
  assert.throws(() => build(one, { "a.com": group("", {}) }), TypeError);
  assert.throws(() => build(one, { "a.com": group(1, {}) }), TypeError);
  assert.throws(() => build(one, { "a.com": group(null, {}), "A.com": group(null, {}) }), /Invalid group mask/);
  assert.throws(() => build(one, { "a.com": group(null, {}), "b.com": group(null, {}) }), /"b\.com" has no root\(\)/);
  assert.throws(() => build(two, { "a.com": group(null, {}) }), /Root "c\.com" has no group/);
  assert.throws(() => build(one, { "a.com": group("b.com", {}) }), /is outside its domain/);
  assert.throws(() => build(one, { "a.com": group(null, { "x.b.com": 1 }) }), /has hosts but no rootHost/);
  assert.throws(() => build(two, { "a.com": group("a.com", { "c.com": 1 }), "c.com": group(null, {}) }), /matches root "c\.com"/);
  assert.throws(() => build(denied, { "a.com": group("www.a.com", { "x.ads.net": 1 }) }), /is under deny "\*\.ads\.net"/);
  assert.throws(() => build(denied, { "a.com": group("www.a.com", { "ads.net": 1 }) }), /"ads\.net" is under deny "\*\.ads\.net"/);
  for (const host of ["localhost", "__proto__", "10.0.0.1", "[::1]"]) {
    assert.throws(
      () => build(one, { "a.com": group("a.com", JSON.parse(`{${JSON.stringify(host)}: 1}`)) }),
      /cannot be learned/,
      host,
    );
  }
});

test("an invalid User PAC is refused before generation", () => {
  assert.throws(() => buildSystemPac("})(); (function () {", {}, PSL), /^Error: User PAC is invalid at 1:1: Unexpected token$/);
  assert.throws(() => buildSystemPac(`#!/bin/pac\n${MAIN}`, {}, PSL), /User PAC is invalid at 1:2/);
  assert.throws(() => buildSystemPac('var root;\n' + MAIN, {}, PSL), /User PAC is invalid at 1:5: Identifier root must not be declared/);
});

test("20 000 hosts build and parse", () => {
  const hosts = {};
  for (let i = 0; i < 20000; i++) hosts[`h${i}.cdn${i % 97}.example.net`] = i;
  const text = build(pacFor("example.com"), { "example.com": { rootHost: "www.example.com", hosts } });
  assert.equal(text.match(/^ {4}".*": 1,?$/gm).length, 20000);
});

test("the User PAC follows its marker line and System PAC lines map back to it", async () => {
  const { userPacLine } = await import("../src/core/build.js");
  const userPac = fixture("user.pac");
  const small = buildSystemPac(userPac, { "instagram.com": { rootHost: null, hosts: {} }, "instagram.com": { rootHost: null, hosts: {} } }, PSL);
  const large = buildSystemPac(userPac, referenceGroups(), PSL);
  const lines = userPac.split("\n").length;
  for (const text of [small, large]) {
    const open = text.split("\n").indexOf("var __user = (function () {") + 1;
    assert.equal(text.split("\n")[open], userPac.split("\n")[0]);
    assert.equal(userPacLine(text, userPac, open + 1), 1);
    assert.equal(userPacLine(text, userPac, open), null);
    assert.equal(userPacLine(text, userPac, 1), null);
    assert.equal(userPacLine(text, userPac, open + lines), lines);
    assert.equal(userPacLine(text, userPac, open + lines + 1), null);
  }
  assert.notEqual(small.split("\n").indexOf("var __user = (function () {"), large.split("\n").indexOf("var __user = (function () {"));
  const crlf = MAIN.replace(/\n/g, "\r\n");
  const crlfPac = buildSystemPac(crlf, {}, PSL);
  assert.equal(userPacLine(crlfPac, crlf, crlfPac.split(/\r\n|\n/).indexOf("var __user = (function () {") + 3), 2);
  const legacy = "var LEARNED_a = {\n};\nvar __user = (function () {\nline one\nline two\nreturn FindProxyForURL;\n})();\n";
  assert.equal(userPacLine(legacy, "line one\nline two", 5), 2);
  assert.throws(() => userPacLine("nothing", "", 1), /no User PAC block/);
});
