import { analyzeUserPac, isValidRoot, parseScript } from "./analyze.js";
import { firstMatch } from "./glob.js";
import { covers, isLearnableName, maskDomain, rootOf } from "./hosts.js";
import { USER_OPEN, userPacLine } from "./pacline.js";

export { userPacLine };


const HEADER = ["// Generated by RootPAC. Do not edit.", "", "(function (global) {"];

const ROUTER = [
  "var __Error = Error;",
  "var __MAX_NAME = 253;",
  "var __MAX_ANSWERS = 64;",
  'var __SCHEMES = [["PROXY", "proxy"], ["HTTPS", "https"], ["SOCKS", "socks"], ["SOCKS4", "socks4"], ["SOCKS5", "socks5"]];',
  "",
  "function __blank(c) {",
  '  return c === " " || c === "\\t";',
  "}",
  "",
  "function __digit(c) {",
  '  return c >= "0" && c <= "9";',
  "}",
  "",
  "function __hex(c) {",
  '  return __digit(c) || (c >= "a" && c <= "f") || (c >= "A" && c <= "F");',
  "}",
  "",
  "function __labelChar(c) {",
  '  return __digit(c) || (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_" || c === "-";',
  "}",
  "",
  "function __slice(text, from, to) {",
  '  var out = "";',
  "  for (var i = from; i < to; i++) out += text[i];",
  "  return out;",
  "}",
  "",
  "function __find(text, from, to, token) {",
  "  for (var i = from; i + token.length <= to; i++) {",
  "    var k = 0;",
  "    while (k < token.length && text[i + k] === token[k]) k++;",
  "    if (k === token.length) return i;",
  "  }",
  "  return -1;",
  "}",
  "",
  "function __tail(text, suffix) {",
  "  var offset = text.length - suffix.length;",
  "  if (offset < 0) return false;",
  "  for (var i = 0; i < suffix.length; i++) {",
  "    if (text[offset + i] !== suffix[i]) return false;",
  "  }",
  "  return true;",
  "}",
  "",
  "function __subdomain(host, domain) {",
  '  return host.length > domain.length && host[host.length - domain.length - 1] === "." && __tail(host, domain);',
  "}",
  "",
  "function __inDomain(host, domain) {",
  "  return host === domain || __subdomain(host, domain);",
  "}",
  "",
  "function __number(text, from, to, digits, limit) {",
  '  if (to - from < 1 || to - from > digits || (to - from > 1 && text[from] === "0")) return false;',
  "  var value = 0;",
  "  for (var i = from; i < to; i++) {",
  "    if (!__digit(text[i])) return false;",
  "    value = value * 10 + +text[i];",
  "  }",
  "  return value <= limit;",
  "}",
  "",
  "function __ipv4(text, from, to) {",
  "  var octets = 0;",
  "  for (var i = from; ; i++) {",
  "    var start = i;",
  '    while (i < to && text[i] !== ".") i++;',
  "    if (!__number(text, start, i, 3, 255)) return false;",
  "    octets++;",
  "    if (i === to) return octets === 4;",
  "    if (octets === 4) return false;",
  "  }",
  "}",
  "",
  "function __ipv6Half(text, from, to, last) {",
  "  var groups = 0;",
  "  for (var i = from; ; i++) {",
  "    var start = i;",
  '    while (i < to && text[i] !== ":") i++;',
  '    if (last && i === to && __find(text, start, to, ".") >= 0) {',
  "      if (!__ipv4(text, start, to)) return -1;",
  "      groups += 2;",
  "    } else {",
  "      if (i - start < 1 || i - start > 4) return -1;",
  "      for (var k = start; k < i; k++) {",
  "        if (!__hex(text[k])) return -1;",
  "      }",
  "      groups += 1;",
  "    }",
  "    if (i === to) return groups;",
  "  }",
  "}",
  "",
  "function __ipv6(text, from, to) {",
  '  var gap = __find(text, from, to, "::");',
  "  if (gap < 0) return __ipv6Half(text, from, to, true) === 8;",
  '  if (__find(text, gap + 2, to, "::") >= 0) return false;',
  "  var head = gap === from ? 0 : __ipv6Half(text, from, gap, false);",
  "  var tail = gap + 2 === to ? 0 : __ipv6Half(text, gap + 2, to, true);",
  "  return head >= 0 && tail >= 0 && head + tail <= 7;",
  "}",
  "",
  "function __hostname(text, from, to) {",
  "  var last = from;",
  "  for (var i = from; ; i++) {",
  "    var start = i;",
  '    while (i < to && text[i] !== ".") i++;',
  "    if (i === start) return false;",
  "    for (var k = start; k < i; k++) {",
  "      if (!__labelChar(text[k])) return false;",
  "    }",
  '    if (i - start >= 4 && (text[start] === "x" || text[start] === "X") && (text[start + 1] === "n" || text[start + 1] === "N") && text[start + 2] === "-" && text[start + 3] === "-") return false;',
  "    last = start;",
  "    if (i === to) break;",
  "  }",
  "  var numeric = true;",
  "  for (var d = last; d < to; d++) {",
  "    if (!__digit(text[d])) numeric = false;",
  "  }",
  '  if (!numeric && to - last >= 2 && text[last] === "0" && (text[last + 1] === "x" || text[last + 1] === "X")) {',
  "    numeric = true;",
  "    for (var x = last + 2; x < to; x++) {",
  "      if (!__hex(text[x])) numeric = false;",
  "    }",
  "  }",
  "  return numeric ? __ipv4(text, from, to) : true;",
  "}",
  "",
  "function __scheme(text, from, to) {",
  "  for (var s = 0; s < __SCHEMES.length; s++) {",
  "    var upper = __SCHEMES[s][0];",
  "    var lower = __SCHEMES[s][1];",
  "    if (to - from !== upper.length) continue;",
  "    var k = 0;",
  "    while (k < upper.length && (text[from + k] === upper[k] || text[from + k] === lower[k])) k++;",
  "    if (k === upper.length) return true;",
  "  }",
  "  return false;",
  "}",
  "",
  "function __server(text, from, to) {",
  "  var i = from;",
  "  while (i < to && !__blank(text[i])) i++;",
  "  if (!__scheme(text, from, i)) return false;",
  "  var gap = i;",
  "  while (i < to && __blank(text[i])) i++;",
  "  if (i === gap || i === to) return false;",
  '  if (text[i] === "[") {',
  "    var close = i + 1;",
  '    while (close < to && text[close] !== "]") close++;',
  "    if (close === to || !__ipv6(text, i + 1, close)) return false;",
  "    i = close + 1;",
  "  } else {",
  "    var start = i;",
  '    while (i < to && !__blank(text[i]) && text[i] !== ":" && text[i] !== "[" && text[i] !== "]") i++;',
  "    if (i === start || !__hostname(text, start, i)) return false;",
  "  }",
  "  if (i === to) return true;",
  '  return text[i] === ":" && text[i + 1] !== "0" && __number(text, i + 1, to, 5, 65535);',
  "}",
  "",
  "var __ANSWERS = { __proto__: null };",
  "var __ANSWER_COUNT = 0;",
  "",
  "function __proxied(result, host) {",
  '  if (typeof result === "string") {',
  "    var known = __ANSWERS[result];",
  "    if (known !== undefined) return known;",
  "  }",
  '  var kept = "";',
  '  if (typeof result === "string") {',
  "    for (var start = 0, i = 0; i <= result.length; i++) {",
  '      if (i < result.length && result[i] !== ";") continue;',
  "      var from = start;",
  "      var to = i;",
  "      while (from < to && __blank(result[from])) from++;",
  "      while (to > from && __blank(result[to - 1])) to--;",
  '      if (__server(result, from, to)) kept += (kept === "" ? "" : "; ") + __slice(result, from, to);',
  "      start = i + 1;",
  "    }",
  "  }",
  '  if (kept === "") throw new __Error("RootPAC: no proxy for " + host + ", direct connection refused");',
  "  if (__ANSWER_COUNT < __MAX_ANSWERS) {",
  "    __ANSWERS[result] = kept;",
  "    __ANSWER_COUNT++;",
  "  }",
  "  return kept;",
  "}",
  "",
  "var __INDEX = { __proto__: null };",
  "",
  "function __entry(name) {",
  "  var entry = __INDEX[name];",
  "  if (entry === undefined) {",
  "    entry = { __proto__: null, root: false, kind: 0, rootHost: null, url: null, bypassHost: false, bypassSubdomain: false };",
  "    __INDEX[name] = entry;",
  "  }",
  "  return entry;",
  "}",
  "",
  "(function () {",
  "  for (var r = 0; r < __ROOTS.length; r++) __entry(__ROOTS[r]).root = true;",
  "  for (var g = 0; g < __GROUPS.length; g++) {",
  "    var group = __GROUPS[g];",
  "    var url = null;",
  "    for (var host in group.hosts) {",
  "      var entry = __entry(host);",
  "      if (entry.kind !== 0) continue;",
  '      if (url === null) url = "https://" + group.rootHost + "/";',
  "      entry.kind = group.hosts[host];",
  "      entry.rootHost = group.rootHost;",
  "      entry.url = url;",
  "    }",
  "  }",
  "  for (var b = 0; b < __BYPASS_HOSTS.length; b++) __entry(__BYPASS_HOSTS[b]).bypassHost = true;",
  "  for (var s = 0; s < __BYPASS_SUBDOMAINS.length; s++) __entry(__BYPASS_SUBDOMAINS[s]).bypassSubdomain = true;",
  "})();",
  "",
  "function FindProxyForURL(url, host) {",
  '  if (typeof host !== "string") throw new __Error("RootPAC: host is not a string");',
  "  var end = host.length;",
  '  while (end > 0 && host[end - 1] === ".") end--;',
  "  if (end < host.length) host = __slice(host, 0, end);",
  "  var underRoot = false;",
  "  var learned = null;",
  "  var bypassed = false;",
  '  var name = "";',
  "  for (var i = host.length - 1; i >= 0 && host.length - i <= __MAX_NAME; i--) {",
  "    name = host[i] + name;",
  '    if (i > 0 && host[i - 1] !== ".") continue;',
  "    var entry = __INDEX[name];",
  "    if (entry === undefined) continue;",
  "    if (entry.root) underRoot = true;",
  "    if (entry.kind === 1 || (entry.kind === 2 && i === 0)) learned = entry;",
  "    if (i === 0 ? entry.bypassHost : entry.bypassSubdomain) bypassed = true;",
  "  }",
  "  if (underRoot) return __proxied(__user(url, host), host);",
  "  if (learned !== null) return __proxied(__user(learned.url, learned.rootHost), host);",
  '  if (bypassed) return "DIRECT";',
  "  return __user(url, host);",
  "}",
  "",
  "function __seal(name, value) {",
  "  Object.defineProperty(global, name, { value: value, writable: false, enumerable: false, configurable: false });",
  "}",
  "",
  '__seal("FindProxyForURL", FindProxyForURL);',
  '__seal("root", function root(host, domain) { return __inDomain(host, domain); });',
  '__seal("deny", function deny(pattern) {});',
  '__seal("bypass", function bypass(pattern) {});',
  "})(this);",
  "",
];

function isPlainObject(value) {
  return typeof value === "object" && value !== null && Object.getPrototypeOf(value) === Object.prototype;
}

function assignNames(masks) {
  const used = new Set();
  const names = new Map();
  for (const mask of masks) {
    const base = `LEARNED_${mask.replace(/[^A-Za-z0-9]/g, "_")}`;
    let name = base;
    for (let k = 2; used.has(name); k++) name = `${base}_${k}`;
    used.add(name);
    names.set(mask, name);
  }
  return names;
}

function checkUserPac(userPac) {
  if (typeof userPac !== "string") throw new TypeError("User PAC must be a string");
  const analysis = analyzeUserPac(userPac);
  if (!analysis.ok) {
    const [{ line, column, message }] = analysis.errors;
    throw new Error(`User PAC is invalid at ${line}:${column}: ${message}`);
  }
  return analysis;
}

function checkGroups(groups, { roots, deny, bypass }) {
  if (!isPlainObject(groups)) throw new TypeError("Groups must be a plain object");
  const masks = Object.keys(groups);
  for (const mask of masks) {
    if (!isValidRoot(mask)) throw new Error(`Invalid group mask ${JSON.stringify(mask)}`);
    if (!roots.includes(mask)) throw new Error(`Group ${JSON.stringify(mask)} has no root() in the User PAC`);
  }
  for (const mask of roots) {
    if (!Object.hasOwn(groups, mask)) throw new Error(`Root ${JSON.stringify(mask)} has no group`);
  }
  for (const mask of masks) {
    const group = groups[mask];
    const label = JSON.stringify(mask);
    if (!isPlainObject(group) || !isPlainObject(group.hosts)) {
      throw new TypeError(`Group ${label} must have a hosts object`);
    }
    const { rootHost } = group;
    if (rootHost !== null && (typeof rootHost !== "string" || rootHost === "")) {
      throw new TypeError(`Group ${label} has an invalid rootHost`);
    }
    if (rootHost !== null && !covers(mask, rootHost)) {
      throw new Error(`Group ${label} rootHost ${JSON.stringify(rootHost)} is outside its domain`);
    }
    for (const host of Object.keys(group.hosts)) {
      const name = JSON.stringify(host);
      if (rootHost === null) throw new Error(`Group ${label} has hosts but no rootHost`);
      if (!isLearnableName(host)) throw new Error(`Host ${name} cannot be learned`);
      const rootMask = rootOf(host, roots);
      if (rootMask !== null) throw new Error(`Host ${name} matches root ${JSON.stringify(rootMask)}`);
      const denyMask = deny.find((mask) => covers(maskDomain(mask), host));
      if (denyMask !== undefined) throw new Error(`Host ${name} is under deny ${JSON.stringify(denyMask)}`);
      const bypassMask = firstMatch(host, bypass);
      if (bypassMask !== null) throw new Error(`Host ${name} matches bypass ${JSON.stringify(bypassMask)}`);
      const covered = bypass.find((mask) => covers(host, maskDomain(mask)));
      if (covered !== undefined) throw new Error(`Host ${name} covers bypass ${JSON.stringify(covered)}`);
    }
  }
}

function renderGroup(mask, name, { rootHost, hosts }, psl) {
  const keys = Object.keys(hosts).sort();
  const body = [
    "  hosts: {",
    ["    __proto__: null", ...keys.map((host) => `    ${JSON.stringify(host)}: ${psl.isPublicSuffix(host) ? 2 : 1}`)].join(",\n"),
    "  }",
  ];
  return [
    `// root: ${JSON.stringify(mask)}`,
    `var ${name} = {`,
    "  __proto__: null,",
    `  rootHost: ${JSON.stringify(rootHost)},`,
    ...body,
    "};",
    "",
  ];
}

function renderArray(name, items) {
  if (items.length === 0) return [`var ${name} = [];`, ""];
  return [`var ${name} = [`, items.map((item) => `  ${item}`).join(",\n"), "];", ""];
}

export function buildSystemPac(userPac, groups, psl) {
  if (typeof psl?.isPublicSuffix !== "function") throw new TypeError("System PAC needs the public suffix list");
  const analysis = checkUserPac(userPac);
  checkGroups(groups, analysis);
  const masks = Object.keys(groups).sort();
  const names = assignNames(masks);
  const bypass = [...new Set(analysis.bypass)].sort();
  const literals = (items) => items.map((item) => JSON.stringify(item));
  const text = [
    ...HEADER,
    ...masks.flatMap((mask) => renderGroup(mask, names.get(mask), groups[mask], psl)),
    ...renderArray("__GROUPS", masks.map((mask) => names.get(mask))),
    ...renderArray("__ROOTS", literals(masks)),
    ...renderArray("__BYPASS_HOSTS", literals(bypass.filter((mask) => !mask.startsWith("*.")))),
    ...renderArray("__BYPASS_SUBDOMAINS", literals(bypass.filter((mask) => mask.startsWith("*.")).map(maskDomain))),
    ...ROUTER,
    USER_OPEN,
    userPac,
    "return FindProxyForURL;",
    "})();",
    "",
  ].join("\n");
  try {
    parseScript(text);
  } catch (error) {
    throw new Error("Generated system PAC does not parse", { cause: error });
  }
  return text;
}
