// Generated by RootPAC. Do not edit.

(function (global) {
// root: "instagram.com"
var LEARNED_instagram_com = {
  __proto__: null,
  rootHost: "www.instagram.com",
  hosts: {
    __proto__: null,
    "edge-chat.facebook.com": 1,
    "scontent-ams2-1.cdninstagram.com": 1,
    "static.cdninstagram.com": 1
  }
};

var __GROUPS = [
  LEARNED_instagram_com
];

var __ROOTS = [
  "instagram.com"
];

var __BYPASS_HOSTS = [];

var __BYPASS_SUBDOMAINS = [];

var __Error = Error;
var __MAX_NAME = 253;
var __MAX_ANSWERS = 64;
var __SCHEMES = [["PROXY", "proxy"], ["HTTPS", "https"], ["SOCKS", "socks"], ["SOCKS4", "socks4"], ["SOCKS5", "socks5"]];

function __blank(c) {
  return c === " " || c === "\t";
}

function __digit(c) {
  return c >= "0" && c <= "9";
}

function __hex(c) {
  return __digit(c) || (c >= "a" && c <= "f") || (c >= "A" && c <= "F");
}

function __labelChar(c) {
  return __digit(c) || (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_" || c === "-";
}

function __slice(text, from, to) {
  var out = "";
  for (var i = from; i < to; i++) out += text[i];
  return out;
}

function __find(text, from, to, token) {
  for (var i = from; i + token.length <= to; i++) {
    var k = 0;
    while (k < token.length && text[i + k] === token[k]) k++;
    if (k === token.length) return i;
  }
  return -1;
}

function __tail(text, suffix) {
  var offset = text.length - suffix.length;
  if (offset < 0) return false;
  for (var i = 0; i < suffix.length; i++) {
    if (text[offset + i] !== suffix[i]) return false;
  }
  return true;
}

function __subdomain(host, domain) {
  return host.length > domain.length && host[host.length - domain.length - 1] === "." && __tail(host, domain);
}

function __inDomain(host, domain) {
  return host === domain || __subdomain(host, domain);
}

function __number(text, from, to, digits, limit) {
  if (to - from < 1 || to - from > digits || (to - from > 1 && text[from] === "0")) return false;
  var value = 0;
  for (var i = from; i < to; i++) {
    if (!__digit(text[i])) return false;
    value = value * 10 + +text[i];
  }
  return value <= limit;
}

function __ipv4(text, from, to) {
  var octets = 0;
  for (var i = from; ; i++) {
    var start = i;
    while (i < to && text[i] !== ".") i++;
    if (!__number(text, start, i, 3, 255)) return false;
    octets++;
    if (i === to) return octets === 4;
    if (octets === 4) return false;
  }
}

function __ipv6Half(text, from, to, last) {
  var groups = 0;
  for (var i = from; ; i++) {
    var start = i;
    while (i < to && text[i] !== ":") i++;
    if (last && i === to && __find(text, start, to, ".") >= 0) {
      if (!__ipv4(text, start, to)) return -1;
      groups += 2;
    } else {
      if (i - start < 1 || i - start > 4) return -1;
      for (var k = start; k < i; k++) {
        if (!__hex(text[k])) return -1;
      }
      groups += 1;
    }
    if (i === to) return groups;
  }
}

function __ipv6(text, from, to) {
  var gap = __find(text, from, to, "::");
  if (gap < 0) return __ipv6Half(text, from, to, true) === 8;
  if (__find(text, gap + 2, to, "::") >= 0) return false;
  var head = gap === from ? 0 : __ipv6Half(text, from, gap, false);
  var tail = gap + 2 === to ? 0 : __ipv6Half(text, gap + 2, to, true);
  return head >= 0 && tail >= 0 && head + tail <= 7;
}

function __hostname(text, from, to) {
  var last = from;
  for (var i = from; ; i++) {
    var start = i;
    while (i < to && text[i] !== ".") i++;
    if (i === start) return false;
    for (var k = start; k < i; k++) {
      if (!__labelChar(text[k])) return false;
    }
    if (i - start >= 4 && (text[start] === "x" || text[start] === "X") && (text[start + 1] === "n" || text[start + 1] === "N") && text[start + 2] === "-" && text[start + 3] === "-") return false;
    last = start;
    if (i === to) break;
  }
  var numeric = true;
  for (var d = last; d < to; d++) {
    if (!__digit(text[d])) numeric = false;
  }
  if (!numeric && to - last >= 2 && text[last] === "0" && (text[last + 1] === "x" || text[last + 1] === "X")) {
    numeric = true;
    for (var x = last + 2; x < to; x++) {
      if (!__hex(text[x])) numeric = false;
    }
  }
  return numeric ? __ipv4(text, from, to) : true;
}

function __scheme(text, from, to) {
  for (var s = 0; s < __SCHEMES.length; s++) {
    var upper = __SCHEMES[s][0];
    var lower = __SCHEMES[s][1];
    if (to - from !== upper.length) continue;
    var k = 0;
    while (k < upper.length && (text[from + k] === upper[k] || text[from + k] === lower[k])) k++;
    if (k === upper.length) return true;
  }
  return false;
}

function __server(text, from, to) {
  var i = from;
  while (i < to && !__blank(text[i])) i++;
  if (!__scheme(text, from, i)) return false;
  var gap = i;
  while (i < to && __blank(text[i])) i++;
  if (i === gap || i === to) return false;
  if (text[i] === "[") {
    var close = i + 1;
    while (close < to && text[close] !== "]") close++;
    if (close === to || !__ipv6(text, i + 1, close)) return false;
    i = close + 1;
  } else {
    var start = i;
    while (i < to && !__blank(text[i]) && text[i] !== ":" && text[i] !== "[" && text[i] !== "]") i++;
    if (i === start || !__hostname(text, start, i)) return false;
  }
  if (i === to) return true;
  return text[i] === ":" && text[i + 1] !== "0" && __number(text, i + 1, to, 5, 65535);
}

var __ANSWERS = { __proto__: null };
var __ANSWER_COUNT = 0;

function __proxied(result, host) {
  if (typeof result === "string") {
    var known = __ANSWERS[result];
    if (known !== undefined) return known;
  }
  var kept = "";
  if (typeof result === "string") {
    for (var start = 0, i = 0; i <= result.length; i++) {
      if (i < result.length && result[i] !== ";") continue;
      var from = start;
      var to = i;
      while (from < to && __blank(result[from])) from++;
      while (to > from && __blank(result[to - 1])) to--;
      if (__server(result, from, to)) kept += (kept === "" ? "" : "; ") + __slice(result, from, to);
      start = i + 1;
    }
  }
  if (kept === "") throw new __Error("RootPAC: no proxy for " + host + ", direct connection refused");
  if (__ANSWER_COUNT < __MAX_ANSWERS) {
    __ANSWERS[result] = kept;
    __ANSWER_COUNT++;
  }
  return kept;
}

var __INDEX = { __proto__: null };

function __entry(name) {
  var entry = __INDEX[name];
  if (entry === undefined) {
    entry = { __proto__: null, root: false, kind: 0, rootHost: null, url: null, bypassHost: false, bypassSubdomain: false };
    __INDEX[name] = entry;
  }
  return entry;
}

(function () {
  for (var r = 0; r < __ROOTS.length; r++) __entry(__ROOTS[r]).root = true;
  for (var g = 0; g < __GROUPS.length; g++) {
    var group = __GROUPS[g];
    var url = null;
    for (var host in group.hosts) {
      var entry = __entry(host);
      if (entry.kind !== 0) continue;
      if (url === null) url = "https://" + group.rootHost + "/";
      entry.kind = group.hosts[host];
      entry.rootHost = group.rootHost;
      entry.url = url;
    }
  }
  for (var b = 0; b < __BYPASS_HOSTS.length; b++) __entry(__BYPASS_HOSTS[b]).bypassHost = true;
  for (var s = 0; s < __BYPASS_SUBDOMAINS.length; s++) __entry(__BYPASS_SUBDOMAINS[s]).bypassSubdomain = true;
})();

function FindProxyForURL(url, host) {
  if (typeof host !== "string") throw new __Error("RootPAC: host is not a string");
  var end = host.length;
  while (end > 0 && host[end - 1] === ".") end--;
  if (end < host.length) host = __slice(host, 0, end);
  var underRoot = false;
  var learned = null;
  var bypassed = false;
  var name = "";
  for (var i = host.length - 1; i >= 0 && host.length - i <= __MAX_NAME; i--) {
    name = host[i] + name;
    if (i > 0 && host[i - 1] !== ".") continue;
    var entry = __INDEX[name];
    if (entry === undefined) continue;
    if (entry.root) underRoot = true;
    if (entry.kind === 1 || (entry.kind === 2 && i === 0)) learned = entry;
    if (i === 0 ? entry.bypassHost : entry.bypassSubdomain) bypassed = true;
  }
  if (underRoot) return __proxied(__user(url, host), host);
  if (learned !== null) return __proxied(__user(learned.url, learned.rootHost), host);
  if (bypassed) return "DIRECT";
  return __user(url, host);
}

function __seal(name, value) {
  Object.defineProperty(global, name, { value: value, writable: false, enumerable: false, configurable: false });
}

__seal("FindProxyForURL", FindProxyForURL);
__seal("root", function root(host, domain) { return __inDomain(host, domain); });
__seal("deny", function deny(pattern) {});
__seal("bypass", function bypass(pattern) {});
})(this);

var __user = (function () {
deny("*.google-analytics.com");
deny("*.doubleclick.net");

var PROXY = "SOCKS5 10.1.4.1:9487";

function FindProxyForURL(url, host) {
  if (root(host, "instagram.com")) return PROXY;
  return "DIRECT";
}
return FindProxyForURL;
})();
